server:
  port: 8080

spring:
  application:
    name: mysterria-api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 15s

gateway:
  backend:
    main:
      url: ${MAIN_BACKEND_URL:http://195.201.242.209:9247}
    archive:
      url: ${ARCHIVE_BACKEND_URL:http://195.201.242.209:8347}

  auth:
    admin:
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:changeme}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    net.mysterria.gateway: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"